version: '3.8'

services:
  app:
    build: .
    container_name: dubai-listings-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://fathiwehba123:fathiwehba123@expresscluster.ikxormq.mongodb.net/dubai-listings?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
      - EMAIL_HOST=smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_USERNAME=your_mailtrap_username
      - EMAIL_PASSWORD=your_mailtrap_password
      - EMAIL_FROM=Dubai Listings <noreply@dubailistings.com>
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
